# Generated by Django 4.2.7 on 2023-12-02 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='item_image',
            field=models.CharField(default='https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQp8MdrNj1NpuBB2kQuEmLxgqn9y3ZZWiAipWbkfzkLIN2DGTQ6U9A7LFQH_i5a1fYjtJg&usqp=CAU', max_length=500),
        ),
    ]
